### ISSUE TITLE
Sistema permitindo cadastro de usuários com mesmo email

### ISSUE THREAD

**Issue by ssisaias** [RobsonCN2015/SAPE-BETA#8]
Sistema está permitindo cadastro de usuários com email repetido.
Problema gera inconsistências no sistema.

**Comment by robsonnegrei** [comment]
Não responde quando é realizado a adição de um usuário sem privilégio.

**Comment by ssisaias** [comment]
Resolvido em 6db3d6d873d04599c464821dbff089af7002dc21

**Comment by robsonnegrei** [comment]
Sistema **Não** redirecionando para _**PCLei/index**_ quando logado com usuario **pclei**.

**Comment by ssisaias** [comment]
@RobsonCN2015 irei corrigir ao concluir a tarefa atual :stuck_out_tongue:

**Comment by ssisaias** [comment]
Corrigido
